"""empty message

Revision ID: 32ce3d8e0693
Revises: 422ce683560a
Create Date: 2020-04-28 07:08:46.660308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ce3d8e0693'
down_revision = '422ce683560a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genre', sa.String(length=50), nullable=True))
    op.add_column('Venue', sa.Column('genre', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genre')
    op.drop_column('Artist', 'genre')
    # ### end Alembic commands ###
