"""empty message

Revision ID: 761fc1fc4d8c
Revises: 32ce3d8e0693
Create Date: 2020-04-28 20:36:59.512838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761fc1fc4d8c'
down_revision = '32ce3d8e0693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
