"""empty message

Revision ID: de8318de717f
Revises: 761fc1fc4d8c
Create Date: 2020-04-28 21:18:35.576798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8318de717f'
down_revision = '761fc1fc4d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
